version: "3.9"
services:
  php-apache:
    container_name: "php-apache"
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
