name: Docker Image CI

on:
  pull_request:
    branches: [ "prod" ]
  workflow_dispatch: 
    

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
       docker build . --file Dockerfile --tag ghcr.io/erwann-dms/groupe5webdev:$(date +%s)
       docker login ghcr.io --username erwann-dms --password ${{secrets.GITHUB_TOKEN}}
       docker push ghcr.io/erwann-dms/groupe5webdev


